map_bundle_generate_map:
    pattern: /administration/map/generate/{parent}
    defaults: { _controller: CitadelMapBundle:Map:generate, parent: null}
    requirements:
        parent: \d{1,4}|null
        
map_bundle_show_map:
    pattern: /administration/map/show/{id}
    defaults: { _controller: CitadelMapBundle:Map:show}
    requirements:
        id: \d{1,4}
