parameters:
  citadel_map.generator.class: Citadel\MapBundle\Services\Generator

services:
  citadel_map.generator:
    class: %citadel_map.generator.class%
    #arguments: [service_id, "plain_value", %parameter%]
