parameters:
  citadel_map.generator.class: Citadel\MapBundle\Services\Generator
  citadel_map.base_image.folder: "Images/Map/Base"

services:
  citadel_map.generator:
    class: %citadel_map.generator.class%
    arguments: [%citadel_map.base_image.folder%]
