<?php

namespace Citadel\MapBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BaseImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BaseImageRepository extends EntityRepository
{
}
